### ISSUE TITLE
Ability to configure users via cloud-config

### ISSUE THREAD

**Issue by zjs** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#100]
/kind feature

**Describe the solution you'd like**
I would like to be able to define information about users as a part of the cloud-config data.

For example, I may want to add a service account with a specific username, SSH authorized key, and group so that I can use to connect to nodes after they have been provisioned.

For example, I may want to restrict the root user's configuration.

**Anything else you would like to add:**

A golang template for configuring this could look something like:
```
{{- if .Users }}
users:
  {{- range .Users }}
  - name: {{ .Name }}
    shell: {{ .Shell  }}
    passwd: {{ .HashedPassword }}
    lock_passwd: {{ .LockPassword }}
    {{- if .Sudo }}
    sudo: {{ .Sudo }}
    {{- end }}
    {{- if .SshAuthorizedKeys }}
    ssh_authorized_keys:
    {{- range .SshAuthorizedKeys }}
      - {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
```

**Comment by detiber** [comment]
This seems quite reasonable, and is also supported in ignition so would not present issues as we look to add support for different output formats.
