### ISSUE TITLE
Add AdditionalCommands field to KubeadmConfigSpec

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#108]
/kind feature

**Describe the solution you'd like**
`ControlPlaneInput` and `NodeInput` both support `AdditionalCommands` in their teamplate and struct but it looks like `KubeadmConfigSpec` does not have a field that the user can use to take advantage of `AdditionalCommands`.

The `AdditionalCommands` field in `KubeadmConfigSpec` should eventually get wired up to `ControlPlaneInput` and `NodeInput`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by chuckha** [comment]
Agreed, we should definitely wire this up.

**Comment by ncdc** [comment]
Would it make sense to be able to specify commands to run both before `kubeadm init/join` and after? Is there a need for a distinction?

**Comment by fabriziopandini** [comment]
@ncdc @chuckha I'm a little bit concerned about the number of request about extending the cloud-init script generation in CABPK outside the boundaries of what is strictly needed by kubeadm.

Instead, why not take this problem from a different perspective, al let CABPK focus on what is strictly necessary for kubeadm and let different infrastructure provider to prepend/append custom extensions to what is generated by CABPK?

**Comment by moshloop** [comment]
I would support the approach of keeping CABPK minimal and letting other bootstrap providers/filters handle extension via chaining - it would also align better with the single responsibility design principle.

**Comment by detiber** [comment]
@moshloop Chaining of bootstrap providers was not in the design for v1alpha2, but it is something that we can discuss for future releases.

@fabriziopandini the potential issue with offloading this to infrastructure providers is that multiple infrastructure providers will likely have to re-implement the same functionality as each other.

We already offer fields that can be abused for non-kubeadm config (AdditionalFiles), I don't necessarily see any issues if we expand that slightly if it provides value for infrastructure provider implementations.
