### ISSUE TITLE
Simplify UX / KubeadmConfig object requirements

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#112]
/kind feature

**Describe the solution you'd like**
The current implementation of CABPK requires the users to comply with some rules for the `KubeadmConfig` object:
- Control plane nodes must have:
  - `InitConfiguration` or` ClusterConfiguration` for the bootstrap control plane
  - `JoinConfiguration`, with `ControlPlane` value set for the additional control planes
- Worker nodes must have:
  - `JoinConfiguration`, with `ControlPlane` value NOT set

While the above requirements are 1:1 with kubeadm requirements, and in some sense also a safeguard around user misconfigurations, we should consider if there are options to make the UX simpler for the users.

What if:
1. we let the reconciler loop to auto-generate a `JoinConfiguration` object if missing? this will allow users to join nodes with a simpler `KubeadmConfig` object
1. we let the reconciler loop to override `JoinConfiguration.ControlPlane` setting according to the machine role? this will make CABPK more tolerant to some users misconfigurations

**Anything else you would like to add:**
This can be eventually considered as an extension of https://github.com/kubernetes-sigs/cluster-api/issues/1227

**Comment by ericzhang08** [comment]
Hi, @fabriziopandini.Can I work on this Issue?

**Comment by chuckha** [comment]
This is fixed

/close
