### ISSUE TITLE
klogr logger does not log

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#113]
/kind bug

**What steps did you take and what happened:**
If you run the default manager you will not see any logs.

**What did you expect to happen:**
I expected to see logs

**Anything else you would like to add:**
I believe a -v flag must be parsed and passed to the klogr instance.

cc @fabriziopandini

**Comment by rudoi** [comment]
`klog.InitFlags()` ruins our lives yet again

**Comment by chuckha** [comment]
@rudoi it does :D
