### ISSUE TITLE
Create secret containing cluster kubeconfig

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#114]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
In v1alpha1, the infrastructure providers could create a secret containing a cluster's kubeconfig. In v1alpha2 the bootstrap provider should handle this.

**Comment by dennisme** [comment]
@rudoi wanna pair on this one?

**Comment by rudoi** [comment]
@dennisme definitely

/assign @dennisme
/lifecycle active
