### ISSUE TITLE
Add a field to the spec called Format

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#121]
/kind feature

**Describe the solution you'd like**
Following up from a discussion https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/11#issuecomment-517698950

We are going to support multiple output versions *after* v1a2 but we are going to add the field now so that we don't have to modify the API later.

Don't forget to regenerate everything after adding the field!

/good-first-issue
/priority important-soon
/milestone v0.1

**Comment by detiber** [comment]
This Format field should probably validate as a ENUM and also default to the value "cloud-config" or maybe "cloud-config", since the cloud-init output we currently produce is in the [Cloud Config Data](https://cloudinit.readthedocs.io/en/latest/topics/format.html#cloud-config-data) format.

**Comment by ykakarap** [comment]
I would like to take up this issue.
/assign @ykakarap

**Comment by ykakarap** [comment]
[This comment](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/11#issuecomment-520843144) suggests that we add the field now. 

In this issue do we only want to add the `Format` field to `KubeadmConfig.Spec` or also add some utility around that field, like read the `Format` field and create an appropriate data generator(?) which in this first implementation will default to cloud init data generator?

@chuckha @detiber

**Comment by detiber** [comment]
@ykakarap The minimum requirement for the feature to be available during the v1alpha2 time frame is that the field is added, since we will not be able to modify fields after the v1alpha2 cut until we start on v1alpha3.

That said, I would not object to the utility work being done prior to the v1alpha2 cut, it just isn't mandatory.

**Comment by chuckha** [comment]
This issue is only around adding the field `Format` to the `Spec`.

Additional issues should be filed to implement the work as we haven't discussed what "the work" actually is yet.
