### ISSUE TITLE
Support for not knowing the control plane endpoint in advance

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#125]
/kind feature

**Describe the solution you'd like**
CAPV, which uses the same bootstrap logic as CAPA, is unique in that vSphere does not have a native load balancer solution. This means that it's not possible to know the control plane endpoint until the first node in the cluster is booted and initialized. For example, in CAPV's model:

1. The bootstrap data for the initial control plane node is generated using JINJA templating similar to what is described in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/490#issuecomment-521009504
2. The initial control plane VM is booted and the control plane is bootstrapped
3. Once the VM hosting the initial control plane node reports its IP address, this address is then recorded as the control plane endpoint for use when generating the bootstrap data for the other members of the cluster (control plane or workers).

This issue is to track this requirement for CAPV and ensure this model is supported by the kubeadm bootstrap provider.

Take the following diagram:

![Machine reconcile workflow](https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-vsphere/master/docs/design/machine-controller-reconcile.svg?sanitize=true)

Not until the step _Update machine status with IP addresses from VM_ occurs for the first control plane node is the control plane endpoint known.

/assign @fabriziopandini

**Comment by neolit123** [comment]
as @fabriziopandini mentioned during the CAPI call this is already supported.
the endpoint can be any FQDN, although the bootstrap provider has to be make sure that only a single CP node gets the privilege call `kubeadm init`. i saw a PR for that in this repo.

the cluster needs to wait for that CP node to finish and then the rest of the nodes *should* be able to join concurrently (CP nodes too).

**Comment by akutz** [comment]
> the endpoint can be any FQDN

At what point do you update the kubeadm conf provider so it treats the IP address from the initial control plane node as the control plane endpoint used to generate the other kubeadm data for subsequent nodes?

**Comment by neolit123** [comment]
the control-plane endpoint can technically be the FQDN of a load balancer which is fixed.
so it can be predefined even before `kubeadm init`, but the requirement would be that the load balancer serves traffic to a set of known IPs for the control-planes.

**Comment by akutz** [comment]
Hi @neolit123,

The case I'm describing is one where **there is no load balancer**.

**Comment by neolit123** [comment]
not having a external load balancer is tricky, maybe there should be one?
the alternative is to use loadbalancer that runs an instance on each node (like keepalived, not sure how these types of LBs are called).

**Comment by akutz** [comment]
> not having a external load balancer is tricky, maybe there should be one?

That's the entire point of this issue @neolit123. It's not like CAPV can flip a switch. The kubeadm bootstrapper must support deploying clusters that don't have an external load balancer. CAPV supports it today, and unless the kubeadm bootstrapper supports it then CAPV will not and cannot move to v1alpha2.

cc @timothysc

**Comment by neolit123** [comment]
> That doesn't solve the problem of an external load balancer that provides an HA control plane.

it's actually more-HA than a VIP load balancer, unless the VIP load balancer is managed by the cloud provider and the cloud provider guarantees that this LB will be always up.

**Comment by akutz** [comment]
The cloud provider has nothing to do with the external load balancer for the API server. The cloud provider is for providing LBs for services.

Please understand that this issue is about:

* The external LB for control plane access
* Completely unrelated to the CPI
* Relevant for all on-prem environments that lack a native LB implementation

Let's not conflate issues or discuss points not germane to this issue.

**Comment by neolit123** [comment]
given there is no LB, how does CAPV currently connect the rest of the control-plane nodes and worker nodes to the cluster?

**Comment by akutz** [comment]
>given there is no LB, how does CAPV currently connect the rest of the control-plane nodes and worker nodes to the cluster? 

 As I described it in the issue description:

> 1. The bootstrap data for the initial control plane node is generated using JINJA templating similar to what is described in kubernetes-sigs/cluster-api-provider-vsphere#490 (comment)
> 2. The initial control plane VM is booted and the control plane is bootstrapped
> 3. Once the VM hosting the initial control plane node reports its IP address, this address is then recorded as the control plane endpoint for use when generating the bootstrap data for the other members of the cluster (control plane or workers).

**Comment by neolit123** [comment]
> Once the VM hosting the initial control plane node reports its IP address, this address is then recorded as the control plane endpoint for use when generating the bootstrap data for the other members of the cluster (control plane or workers).

if the primary control-plane node fails where would the rest of the worker and control-plane nodes connect to? would that result in cluster failure?

**Comment by moshloop** [comment]
The way in which https://kubespray.io/#/docs/ha-mode describe it is as `localhost loadbalancing` 

Kubespray requires all the control node IP's to be known beforehand to setup the localhost loadbalancer,
I have setup something similar that I call `client-side load balancing` that uses an external consul cluster for master service discovery

In both these scenarios the kubelet, etc use `localhost` as the control plane endpoint

**Comment by akutz** [comment]
Hi @neolit123,

> if the primary control-plane node fails where would the rest of the worker and control-plane nodes connect to? would that result in cluster failure?

I feel like perhaps you're unfamiliar with CAPV and the environmental constraints within which CAPV operates. I'd be happy to sit down and review CAPV with you sometime.

vSphere has no native LB support. That's why CAPV doesn't have support for HA clusters yet. Your observation is correct, but CAPV is operating within the parameters of what vSphere has to offer. We've discussed deploying a third-party LB solution, and in fact that is what Moshe discussed today during the CAPI call.

I want to keep this issue on track though, and note that we're not here to debate what CAPV does within the constrains it operates.

We're here to discuss support for:

* DHCP environment where IPs are not known in advance
* And the initial control plane node's IP is the control plane endpoint
* And how to make the kubeadm bootstrapper work for that

**Comment by akutz** [comment]
> The way in which https://kubespray.io/#/docs/ha-mode describe it is as `localhost loadbalancing`
> 
> Kubespray requires all the control node IP's to be known beforehand to setup the localhost loadbalancer,
> I have setup something similar that I call `client-side load balancing` that uses an external consul cluster for master service discovery
> 
> In both these scenarios the kubelet, etc use `localhost` as the control plane endpoint

This is not the problem domain. The problem domain is as described in the original description and clarified above:

> We're here to discuss support for:
>
> * DHCP environment where IPs are not known in advance
> * And the initial control plane node's IP is the control plane endpoint
> * And how to make the kubeadm bootstrapper work for that

**Comment by neolit123** [comment]
> The way in which https://kubespray.io/#/docs/ha-mode describe it is as localhost loadbalancing

i guess this naming makes some sense, although the control-planes can still connect to a VIP instead of localhost.

**Comment by neolit123** [comment]
> I want to keep this issue on track though, and note that we're not here to debate what CAPV does within the constrains it operates.

it's certainly presenting an interesting challenge.

**Comment by moshloop** [comment]
For client-side loadbalancers, the **VIP is `localhost`** which is known in advance.

What this issue describes is a case where the **VIP is a DHCP assigned IP** not known until the first control plane endpoint is up.

This issue would likely require a new cluster phase e.g. "init" that allows the first control plane node to be created, but waits for the other control plane nodes until the first control plane nodes IP is known.

**Comment by akutz** [comment]
> it's certainly presenting an interesting challeng

> This issue would likely require a new cluster phase e.g. "init" that allows the first control plane node to be created, but waits for the other control plane nodes until the first control plane nodes IP is known.

Except it's not *that* interesting or unsolved. CAPV does this today by basically ensuring the control plane is online before any other node is allowed to join. Much like CAPA does. Andy and I solved it the same way. The only difference is that at the end of the the init phase, the IP of the first node is recorded and used as the control plane endpoint for the other nodes.

It's a solved problem space (albeit one no one seems to grok because an external, existing LB endpoint seems to be an assumption people are unable to put to the side for a moment). This issue is to ensure the kubeadm bootstrap provider supports the solution, or CAPV cannot use CAPI v1alpha2.

**Comment by moshloop** [comment]
> end of the the init phase

This implies serial, synchronous provisioning of the machines which is not ideal

**Comment by akutz** [comment]
Hi @moshloop,

> This implies serial, synchronous provisioning of the machines which is not ideal

It implies bringing up a *single* machine first, which is what *already happens with the control plane nodes anyway*.

**Comment by fabriziopandini** [comment]
@akutz CABPK should already support your requirement and more specifically

> Once the VM hosting the initial control plane node reports its IP address, this address is then recorded as the control plane endpoint for use when generating the bootstrap data for the other members of the cluster (control plane or workers).

CABPK will start to use cluster.APIEndpoint as soon as it is available, and this can happen in two moments, depending on the infrastructure provides specific implementation:
- before setting InfrastructureReady (e.g. a cloud provider with LB)
- before setting controlplaneReady (your use case)

FYI, this is the workflow currently implemented

- When cluster.InfrastructureReady == true, It creates cloud-init for the bootstrap control plane; following rules apply:
   - if the controlPlaneEndpoint is not empty, it is used
   - if the controlPlaneEndpoint is empty and exists an entry in cluster.APIEndpoint, the cluster.APIEndpoint is used as controlPlaneEndpoint.
   - if controlPlaneEndpoint is empty and there are no cluster.APIEndpoint, kubeadm init will use the ip of the machine as  controlPlaneEndpoint, but in this case, you should be aware that you can't add more control plane nodes.
- When cluster.controlplaneReady == true, It creates cloud-init for the joining nodes; following rules apply:
   - if exists an entry in cluster.APIEndpoint, the cluster.APIEndpoint is used as join address.
   - if there are no cluster.APIEndpoint, it requeues (this is for tolerating delay in the cluster.APIEndpoint being set)

**Comment by andrewsykim** [comment]
@moshloop commented on your client-side loadbalancing comment here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/245#issuecomment-521404254, let's continue that discussion there. 

@fabriziopandini, sorry if I'm missing anything here, I'm still learning about v1alpha2:

> if controlPlaneEndpoint is empty and there are no cluster.APIEndpoint, kubeadm init will use the ip of the machine as controlPlaneEndpoint, but in this case, you should be aware that you can't add more control plane nodes.

I'm curious why ^ this check happens at `InfrastructureReady` check and not the `ControlPlaneReady` check?

**Comment by fabriziopandini** [comment]
@andrewsykim 
CABPK uses the cluster state machine in order to understand when it is legit to do `kubeadm init` or to do `kubeadm join`

`InfrastructureReady` (and not `ControlPlaneReady`) --> time for `kubeadm init` (all the join request are requeued)
`InfrastructureReady` and `ControlPlaneReady` --> time for `kubeadm join` (all the init request are rejected)

The case you highlighted, is a supported scenario for `kubeadm init` (init without a LB/stable controlplaneEndpoint)

PS. feel free to ping me on slack if this is not clear enough

**Comment by moshloop** [comment]
> kubeadm init will use the ip of the machine as controlPlaneEndpoint, but in this case, you should be aware that you can't add more control plane nodes.

This is the problem, as adding more control plane nodes is precisely what is required, but perhaps this is kubeadm issue instead?

Creating a fully HA cluster without an external service would be possible only if this issue is resolved.

e.g. 
1. Create `control plane 1`
2. Set `controlPlaneEndpoint` to `control plane 1`'s ip
3. Create `control plane 2-3` which use's the single IP to form a gossip based cluster (the approach kops uses without an external dns coordinator) - Once created the first control plane node can go down without affecting the availability of the cluster
4. Expose `default/kubernetes` API service on a stable endpoint via MetalLB or ExternalDNS

**Comment by fabriziopandini** [comment]
@mishloop
Gossip based cluster, metalLB, external dns IMO are out of the scope of both kubeadm and CABPK

**Comment by moshloop** [comment]
I agree for kubeadm, but not for CABPK, CABPK doesn't need to configure or manage these, but it shouldn't prevent them either.

**Comment by chuckha** [comment]
@akutz I have some thoughts here but I'd like to better understand the problem.

This is how I see it working, it's all supported today, so I'd like to know what I'm missing:

1. Create the YAML necessary to stand up a control-plane node.
2. Apply YAML to the management server
3. Wait for the control plane to come online. CAPI will record the APIEndpoint of this control plane.
4. Create more kubeadm configs for more machines and join them to the cluster.
5. CABPK will pick up the APIEndpoint that of the cluster, assuming they are linked correctly and use that to join the cluster.

It seems with no load balancer available that multi-node control planes don't make sense in this environment so I have omitted the step of creating multiple control-plane nodes.

I'm sure I've made some bad assumptions in this workflow and am looking for corrections so I can understand what your needs are.

**Comment by akutz** [comment]
Hi @chuckha,

> @akutz I have some thoughts here but I'd like to better understand the problem.
> 
> This is how I see it working, it's all supported today, so I'd like to know what I'm missing:
> 
> 1. Create the YAML necessary to stand up a control-plane node.

Sí.

> 2. Apply YAML to the management server

Sí.

> 3. Wait for the control plane to come online. CAPI will record the APIEndpoint of this control plane.

Sí.

> 4. Create more kubeadm configs for more machines and join them to the cluster.

Sí.

> 5. CABPK will pick up the APIEndpoint that of the cluster, assuming they are linked correctly and use that to join the cluster.

Sí.

> It seems with no load balancer available that multi-node control planes don't make sense in this environment so I have omitted the step of creating multiple control-plane nodes.
> 
> I'm sure I've made some bad assumptions in this workflow and am looking for corrections so I can understand what your needs are.

Sí.

You nailed it. Although, wouldn't it be nice if there were diagrams to help understand the workflow. Oh, wait, there are. Basically because I myself couldn't keep track of it without pretty pictures :)

**Cluster admission - cluster loop**

![Cluster admission - cluster loop](https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-vsphere/master/docs/design/cluster-admission-cluster-controller.svg?sanitize=true)

**Cluster admission - machine loop**

![Cluster admission - cluster loop](https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-vsphere/master/docs/design/cluster-admission-machine-controller.svg?sanitize=true)

**Comment by akutz** [comment]
Thank you @chuckha and @fabriziopandini for confirming support!

/close

**Comment by detiber** [comment]
Are there any additional blockers for this, other than https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/143?

**Comment by vincepri** [comment]
See #190

**Comment by ncdc** [comment]
Now that https://github.com/kubernetes-sigs/cluster-api/pull/1345 is in, is there anything else outstanding before we can close this?

**Comment by vincepri** [comment]
@akutz Closing this for now, feel free to reopen if needed

/close

**Comment by akutz** [comment]
Hi @vincepri,

Thank you. @ykakarap should be testing this this afternoon. I really appreciate you handling this!
