### ISSUE TITLE
Modify cert secret to be 1 secret per cert 

### ISSUE THREAD

**Issue by dennisme** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#135]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
In  https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/126 certificate generation and secret lookup was added to the bootstrap controller. We had a discussion on the secret format related to cert-manager. In order to support cert-manager we will need 1 secret per cert. 

See details here: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/126#discussion_r314039485

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by chuckha** [comment]
I opened #133 to address this -- happy to keep yours instead, but we should close one of them

**Comment by chuckha** [comment]
let's keep this one

**Comment by ncdc** [comment]
@moshloop do you have any updates on this?

**Comment by moshloop** [comment]
I should have a PR submitted but the meeting tomorrow.
