### ISSUE TITLE
Add OwnerRef to kubeconfig secret (can't delete it)

### ISSUE THREAD

**Issue by dennisme** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#149]
/kind bug
/assign

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Create and attempt to delete kubeconfig secret. 

**What did you expect to happen:**
Deleting the kubeadmconfig should delete the kubeconfig secret too.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API version:
- Cluster API Bootstrap Provider Kubeadm version:
- Cluster API Infrastructure Provider version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
@dennisme There was a discussion yesterday where there was consideration to move the management of the kubeadm secret to the cluster-api Cluster controller instead of here, see: https://github.com/kubernetes-sigs/cluster-api/issues/1274

**Comment by dennisme** [comment]
@detiber good point, I was debating on doing this just to speed up my local debugging as I create a tear down a bunch of clusters today.

**Comment by ncdc** [comment]
If we move the secret generation to CAPI, we can close this (and address the deletion/ownerRef in CAPI).

**Comment by chuckha** [comment]
Kubeconfig is no longer created by this provider.

/close
