### ISSUE TITLE
Create schema for KubeadmConfig object

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#15]
/kind feature

**Describe the solution you'd like**
For now we are following the agreed upon spec from https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190610-machine-states-preboot-bootstrapping.md#sequence-diagram-user-creates-a-machine-with-kubeadm-bootstrapper.

The KubeadmConfig needs to be filled out.

/cc @amy @rudoi 

**Anything else you would like to add:**

**Comment by neolit123** [comment]
please assign @fabriziopandini for review once there are PRs out there.
thanks.
