### ISSUE TITLE
Implement the controller logic for cloud-init output

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#16]
/kind feature

**Describe the solution you'd like**
The output of this can be deduced from this paragraph in the cluster api proposal:

> Upon receiving a Machine event, a reconcile request is enqueued for the associated KubeadmBootstrapConfig. Next, it retrieves the Machine, Cluster, and generates a cloud-init based bootstrap configuration which is then stored in KubeadmBootstrapConfig.Status.BootstrapData. It also sets KubeadmBootstrapConfig.Status.Phase to “Ready”. A non-nil value in KubeadmBootstrapConfig.Status.BootstrapData is indicative to the Cluster API Machine Controller that the bootstrap provider has completed its work.

This means cloud-init is the first output. This does NOT mean cloud-init is the only output but it's a good way for us to get started.

**Anything else you would like to add:**

**Comment by amy** [comment]
Lets split this up in 2 parts:

- [ ] Controller Logic
- [ ] Generating cloud-init configuration

We can use this issue to just track the progress of the controller logic part.
