### ISSUE TITLE
enable staticcheck for this repo

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#160]
/kind feature
/priority backlog

k/k just enabled running staticcheck, while the k-sigs/kind repo had it for a while already.
you can check what k/k is doing in terms of skipping certain checks (if this repo has to).
see /hack/verify-staticcheck.sh in kubernetes/kubernetes.

we are enabling this for k/kubeadm/kinder too:
https://github.com/kubernetes/kubeadm/pull/1737

/help

mini-guide:
- create a shell script under /hack called verify-staticcheck.sh that builds and executes staticcheck
- include the script in hack/verify-all.sh
- create PR with first commit that adds the above 2 changes
- create separate commit that fixes the discovered staticcheck problems.
- if certain checks are problematic (e.g. in generated code), skip them.

(possibly the same has to be done for the docker provider repo).

**Comment by SataQiu** [comment]
If nobody claims it, I will pick this up. 
Wait a while for new contributors :-)

**Comment by joonas** [comment]
What about using [golangci](https://github.com/golangci/golangci-lint/) for this?

[CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/master/.golangci.yml) and [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/.golangci.yml) already have this configured for them, so using golangci would be nice for getting consistency across the various repositories
