### ISSUE TITLE
Rename type Files into File

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#169]
/kind bug

**What steps did you take and what happened:**
`KubeadmConfig` object contains a field `Files []Files` which I feel a little bit awkward considering that the `Files` type actually describes a single additional file.

**What did you expect to happen:**
The `Files` type be renamed into `File` (singular)

**Comment by detiber** [comment]
Just wanted to add a note that since this affects the API types, this change could only land with a version targeting a new API version.

**Comment by ncdc** [comment]
As long as this gets in before we release v1alpha2, we can do this, right?

**Comment by SataQiu** [comment]
If no one claims it, I'd like to pick it up.
Wait a while for new contributors! 
Feel free to self-assign :)

**Comment by ncdc** [comment]
Please feel free to take it on

**Comment by detiber** [comment]
> As long as this gets in before we release v1alpha2, we can do this, right?
Correct, just wanted to make it clear that if it didn't make the release it would have to wait for v1alpha3 :)
