### ISSUE TITLE
Initial README

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#19]
/kind documentation

**Describe the solution you'd like**
Add something to the README. Keep it short and informative. Do not use many words. Consider commenting on this issue about ideas for future documentation that we might keep in a docs directory.

/cc @amy

**Comment by amy** [comment]
On my radar, but it's cool if someone gets to this before me!

**Comment by detiber** [comment]
@chuckha looks like you need to configure the repo_milestone prow plugin for the repo here: https://github.com/kubernetes/test-infra/blob/973a6e61255a7a94ae6023c6802610f23b2a82a4/prow/plugins.yaml#L239

**Comment by fabriziopandini** [comment]
ideas for docs directory:
- getting started guide for local development
- doc about cloud-init generation principles (e.g. cloud/os agnostic, file injection, template structure)
