### ISSUE TITLE
Steps to create cluster,machine,dockermachine

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#193]
/kind bug
Could it be clarified how the steps to create the cluster,machine should be executed.
Is that using the clusterctl command ? which yaml corresponds to which parameter in this case ?
./clusterctl create cluster --provider <provider> --bootstrap-cluster-kubeconfig <kubeconfig> \
  -c cluster.yaml -m machines.yaml -p provider-components.yaml -a addons.yaml

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API version:
- Cluster API Bootstrap Provider Kubeadm version:
- Cluster API Infrastructure Provider version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@sb1975 are you still looking for an answer to this?

**Comment by ncdc** [comment]
Closing due to age and because we are in the process of rewriting clusterctl from scratch, and this question is not applicable to the new version due to changes.

/close
