### ISSUE TITLE
Set up automated tests

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#2]
Get the normal hack/ scripts in place and set them up in prow

**Comment by chuckha** [comment]
I think this is a very clean implementation of what I'm talking about: https://github.com/kubernetes-sigs/cluster-api-provider-docker/tree/master/hack

**Comment by vincepri** [comment]
As part of this work, can we use go modules given that this targets v1alpha2?

**Comment by neolit123** [comment]
yes, certainly.
the CI will need to manage a go deps test, so i'm going to add some placeholders as a start.

**Comment by neolit123** [comment]
/remove-lifecycle active.
will leave open if something else is needed.

**Comment by chuckha** [comment]
/close

thanks for fixing this! it's all working
