### ISSUE TITLE
Do not single-quote additional commands

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#201]
/kind bug

**What steps did you take and what happened:**
Commands given to the cloud-init `runcmd` module are currently [single-quoted](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/e3b2bcf70c84fed5ca2e0030e5b96fef6ee6aa83/cloudinit/commands.go#L22):

```yaml
runcmd:
  - 'hostname '{{ ds.meta_data.hostname }}''
```

This causes issues when strings inside the commands are themselves single-quoted. The above example *should* be emitted like so:

```yaml
runcmd:
  - hostname '{{ ds.meta_data.hostname }}'
```

**What did you expect to happen:**
The commands should not be quoted at all, per the [cloud-init docs](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot), ex:

```yaml
#cloud-config

# run commands
# default: none
# runcmd contains a list of either lists or a string
# each item will be executed in order at rc.local like level with
# output to the console
# - runcmd only runs during the first boot
# - if the item is a list, the items will be properly executed as if
#   passed to execve(3) (with the first arg as the command).
# - if the item is a string, it will be simply written to the file and
#   will be interpreted by 'sh'
#
# Note, that the list has to be proper yaml, so you have to quote
# any characters yaml would eat (':' can be problematic)
runcmd:
 - [ ls, -l, / ]
 - [ sh, -xc, "echo $(date) ': hello world!'" ]
 - [ sh, -c, echo "=========hello world'=========" ]
 - ls -l /root
 # Note: Don't write files to /tmp from cloud-init use /run/somedir instead.
 # Early boot environments can race systemd-tmpfiles-clean LP: #1707222.
 - mkdir /run/mydir
 - [ wget, "http://slashdot.org", -O, /run/mydir/index.html ]
```

**Comment by chuckha** [comment]
Closing as a duplicate:

https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/192

Will add a note about quoting there since some quoting is required as per the docs. Anything that YAML would get confused by needs quotes.
