### ISSUE TITLE
Testing for expected behaviors

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#214]
/kind feature

**Describe the solution you'd like**
We've done a decent job of testing very important behaviors but I'd like to add some more tests for a few more behaviors listed here:

⚠️ In order to view the [original document](https://docs.google.com/document/d/1g6xxhD_AFA4klrm87f7o0XpEtOOZfbSIat3ltKmbvrc/edit
) please join the [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) or the [kubernetes-sig-cluster-lifecycle](https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle) google groups. ⚠️

The tests I'd like to see added are:

Note, you may be able to argue some of these exist or I may have missed some scenarios and these don't need implementing. That is ok too!

## Tests

- [x] Return early if the owning machine does not have an associated cluster (@hpandeycodeit https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/240)
- [x] Return early if the cluster’s infrastructure is not ready (@sb1975)
- [x] Exactly one control plane machine initializes if there are multiple control plane machines defined (there are tests for the lock but not explicit tests here) (@SataQiu https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/221)
- [x] Uses existing certificate secrets (@Xenwar https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/235)
- [ ] Generates a valid cloud-config (**TODO**)
  - [ ] Include characters that require escaping (**TODO**)
- [x] Triggers a reconcile for an associated KubeadmConfig when a Machine that references it is modified (@mikkosest #237 )
- [x] Triggers a reconcile for all KubeadmConfigs associated with all Machines associated with a modified Cluster. (@chuckha #216)

**Comment by hpandeycodeit** [comment]
I will work on `Return early if the owning machine does not have an associated cluster ` :)

**Comment by Xenwar** [comment]
Do I take 'Uses existing certificate secrets' ?
thanks.

**Comment by chuckha** [comment]
@Xenwar Sure thing! let me know if you have any questions or need help, I'm `@cha` on the k8s slack.

**Comment by sb1975** [comment]
Reg this Test :  Return early if the cluster’s infrastructure is not ready (TODO)
Does it mean I need to validate that the infrastructure like the KIND k8s cluster(or any other provider master/bootstrap cluster is ready) before a tenant(workload) cluster can be created ?
That is there should be an error at early stage when we try to create a workload cluster if these infrastructure components(Can we call out which components we mean here please) are not ready ?
Once I have clarity I am willing to take this up :)

**Comment by chuckha** [comment]
@sb1975 The scope of these tests all fall within the [Reconcile function](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/cc2b1e48885f2f7bda4b8a3048b1c33367322a0f/controllers/kubeadmconfig_controller.go#L89)

In short, I want to ensure this path is followed https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/cc2b1e48885f2f7bda4b8a3048b1c33367322a0f/controllers/kubeadmconfig_controller.go#L135-L138 when the boolean value holds true.

**Comment by SataQiu** [comment]
I'd like to work with 
```
Exactly one control plane machine initializes if there are multiple control plane machines defined
```

**Comment by chuckha** [comment]
@SataQiu Excellent, thank you!

**Comment by chuckha** [comment]
I'm going to pick up

```
 Triggers a reconcile for all KubeadmConfigs associated with all Machines associated with a modified Cluster.
```

**Comment by mikkosest** [comment]
Can I take "Triggers a reconcile for an associated KubeadmConfig when a Machine that references it is modified (TODO)" ? BR Mika

**Comment by chuckha** [comment]
@mikkosest yes, absolutely!

**Comment by kashifest** [comment]
@chuckha  I am interested to take "Return early if the cluster’s infrastructure is not ready"

**Comment by chuckha** [comment]
@kashifest spoke offline and he's going to pick up a different issue,  #212 to be exact

**Comment by ashish-amarnath** [comment]
@sb1975 I picked up 
> Return early if the cluster’s infrastructure is not ready
PR #277

**Comment by chuckha** [comment]
Let's close this, really nice work everyone!! Thank you all for your contributions!

/close
