### ISSUE TITLE
Extract golint into a tool in hack/tools

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#223]
/kind feature

**Describe the solution you'd like**
The golint tool is used to lint our codebase. It's being installed in a tempdir but it should follow the existing pattern of tools.

The hack/verify-golint.sh file should not be doing any of this:

https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/23205b40552da0c99f822458aa02a97df583d5e4/hack/verify-golint.sh#L39-L50

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Perhaps it's entirely replaced with golangci-lint?

https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/tree/master/hack/tools

That is for the ticket owner to decide. 
/priority important-soon
/milestone v0.1.x

**Comment by SataQiu** [comment]
Hi @chuckha Is anyone doing this?
I think I can help with this.
