### ISSUE TITLE
MachineWatch is wrong

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#227]
/kind bug

**What steps did you take and what happened:**
In the process of going through #214, @mikkosest discovered our machine watch is incorrect. It is using `util.MachineInfrastructureRef` when it should not be using that but should be checking for BootstrapRef instead.

@mikkoset will be writing a test and a new MapFunc to fix this behavior

Thanks so much!!

/assign @mikkoset
/lifecycle active
/priority important-soon
/milestone v0.1.x

**Comment by mikkosest** [comment]
I will start with this
