### ISSUE TITLE
verify-boilerplate does not tolerate copyright lines without year

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#23]
/kind bug
/assign

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

copyright lines in generated files (created by the k8s code-gen) tools don't have years.
this makes the verify boilerplate check fail.

support copyright lines without year for autogenerated files.

https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/22#issuecomment-510644042

**Comment by vincepri** [comment]
We should move to the same utilities we have upstream https://github.com/kubernetes-sigs/cluster-api/blob/master/hack/verify-boilerplate.sh https://github.com/kubernetes-sigs/cluster-api/tree/master/hack/boilerplate which are copied from k/k :D

**Comment by ashish-amarnath** [comment]
I had the same idea. I’ll replace the go code w/ the python script from k/k

**Comment by neolit123** [comment]
i guess it's fine to match cap* repos to use the same boilerplate code.
probably someone did not understand go and wrote it in python.

i will keep this in kinder and possibly etcdadm.

**Comment by moshloop** [comment]
While perhaps not the right repo/issue does it not make sense to introduce a SCL go package/binary to handle these types of `hack` script related tasks?

Maybe something based off https://github.com/google/addlicense / https://github.com/fbiville/headache and then later extended to handle:

* dependency downloads (controller-gen, gitbook, etc..)
* linting
* doc / api generation 
* etc..

Bash and python get the job done for a monorepo, but for multiple repos it quickly becomes a headache

**Comment by detiber** [comment]
Personally, I would like to see something for the greater k8s ecosystem, such as https://github.com/kubernetes/repo-infra, but usable without `git subtree` or other hackery.

**Comment by neolit123** [comment]
WRT to this ticket just switch to the PY version of the boilerplate check from k/k.

**Comment by chuckha** [comment]
I don't think there's anything else to be done with this issue. New files should have a year, generated files that do not have a year are excluded from the check.

/close
