### ISSUE TITLE
Control plane init unlocking is happening in the wrong spot and is too noisy

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#233]
/kind bug

The control plane init locker unlock call happens in [EVERY case](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/46acfbd87f80e1de985d5ece090be0197823d226/controllers/kubeadmconfig_controller.go#L165) when it should only happen in the[ control plane initialization code](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/46acfbd87f80e1de985d5ece090be0197823d226/controllers/kubeadmconfig_controller.go#L172) at the very beginning.

Because of this the lock is unnecessarily noisy. I think we can start by moving the ulocking to the initialization code path only and if the logs continue to be noisy we can definitely remove the info logs as they are `Info` logging when no helpful information is actually being given. For instance, we don't care that the control plane lock could not be found and yet we log it anyway.

/good-first-issue
/help
/priority important-soon
/milestone v0.1.x

**Comment by chuckha** [comment]
cc @lokicity

**Comment by chuckha** [comment]
It appears #232 is already open 

/lifecycle active
/assign @accepting

**Comment by Lokicity** [comment]
@chuckha @accepting Thank you for looking at this issue. In my case, looks like the code stuck at ```I0917 06:18:06.486453       1 control_plane_init_mutex.go:112] init-locker "level"=0 "msg"="Control plane init lock not found, it may have been released already" "cluster-name"="capi-quickstart-bar" "configmap-name"="capi-quickstart-bar-lock" "namespace"="bar" ``` and the worker node is unable to be created.

**Comment by chuckha** [comment]
@Lokicity That log line can be ignored and should not be the thing preventing workers from joining or being created. Are you able to look at the cloud-init logs for the control plane? Perhaps is not being created correctly or it is unable to join nodes for some other reason?

**Comment by chuckha** [comment]
This got fixed by #232 
/close
