### ISSUE TITLE
Does not support a custom pki directory

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#255]
/kind bug

**What steps did you take and what happened:**
Kubeadm allows for [custom CertificatesDir](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/kubeadm/v1beta1/types.go#L107), but we hardcode it to `/etc/kubernetes/pki`.

**What did you expect to happen:**
I expect CABPK to respect my kubeadm config.

this is not a super common feature from my experience in kubeadm but we should support it as people will expect this to work

/priority important-longterm
/milestone Next

**Comment by ashish-amarnath** [comment]
Where would the custom certificates dir be supplied for controlplane joins?
[CACertPath](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/kubeadm/v1beta1/types.go#L323) points only to the ca cert.

**Comment by chuckha** [comment]
@ashish-amarnath to answer your question fully: This only applies to control plane nodes, not to worker nodes. Worker nodes only need the ca.crt file to work whereas the control plane needs the entire set of certs
