### ISSUE TITLE
verify-all is exiting 0 when one or more verification script is failing

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#35]
/kind bug

**What steps did you take and what happened:**
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-bootstrap-provider-kubeadm/33/pull-cluster-api-bootstrap-provider-kubeadm-verify/1151447199930912768/build-log.txt

This run has failing validations but results in `All verify checks pass!". How could this happen?

**What did you expect to happen:**
I expect a build failure.

**Anything else you would like to add:**
I cannot reproduce this locally. I checked out the referenced code and ran ./hack/verify-all.sh and the exit code is very reliably 1 always.

/cc @neolit123

**Comment by neolit123** [comment]
> error validating "controllers/control_plane_init_locker.go": boilerplate line 2 does not match
expected: ""
got: "Licensed under the Apache License, Version 2.0 (the \"License\");"

seems there are licensing problems. why is this file licenses in such a way?

you can just try the Python boilerplate at this point, but the file doesn't seem to follow the recommended boilerplate anyhow.

**Comment by ashish-amarnath** [comment]
IMHO, we should prefer consistency across repos for something like this.
I can re-open https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/24 if there is a consensus.

**Comment by chuckha** [comment]
@ashish-amarnath yes, consistency would be nice, @neolit123 and I have been going back and forth on that but haven't really come to much consensus. Any ideas for how to make this doable would be great, but that's out of scope for this ticket. We need to address why our verify scripts are returning 0 when some checks fail. I am wondering if it has to do with the way the script is run in prow/kubekins? since I cannot reproduce it locally.

**Comment by ncdc** [comment]
Should be fixed. Please reopen if needed.
/close
