### ISSUE TITLE
Add a KubeadmClusterBootstrapConfig type

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#46]
/kind feature

**Describe the solution you'd like**
We should consider adding a cluster-wide configuration type, maybe called `KubeadmClusterBootstrapConfig`, to hold data that does not vary across machines.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by vincepri** [comment]
s/KubeadmClusterBootstrapConfig/KubeadmClusterConfig?

**Comment by ncdc** [comment]
Naming TBD pending bikeshedding 😄

**Comment by ncdc** [comment]
Talked to @fabriziopandini and @chuckha on Zoom. We shouldn't need this. The first control plane machine can use ClusterConfiguration + InitConfiguration. All subsequent machines can use JoinConfiguration.
