### ISSUE TITLE
During bootstrap, deploy a user-defined set of addons.

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#50]
/kind feature

**Describe the solution you'd like**
During bootstrap, deploy a user-defined set of addons.

**Anything else you would like to add:**
Today, the CAPI control plane uses workload cluster's API to deploy addons. This requires the CAPI control plane to reach the workload cluster's API directly.

End-users want to deploy workload clusters in networks that restrict ingress from the internet (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/873), which can prevent CAPI controllers from reaching the workload cluster's API.

There are many ways to solve the workload cluster API reachability problem, but software solutions (typically a client-server pair) would be best deployed as Pods in the management and workload clusters.

Limiting the addons deployed at bootstrap to Static Pods seems like a viable option.

**Comment by dlipovetsky** [comment]
Some x-refs. 
1. Solution could be the same as CAPA's support for "additional configuration files" (with some caveats): https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/847
1. Security implications of static pods on non-control plane machines: https://github.com/kubernetes/kubeadm/issues/1541

**Comment by dlipovetsky** [comment]
@cha Any thoughts on whether additional static pods (or, generally, additional configuration files) are in scope? Is it better to implement this as a "node lifecycle hook" (lifecycle hooks will be supported by CAPI in the future).

**Comment by dlipovetsky** [comment]
Regardless of where this is implemented (CABPK, kubeadm config, some node lifecycle hook), the user-defined set of addons looks like it will end up in cloud-init user-data. And as CAPA learned from https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/847, the infrastructure might limit user-data size. For example, AWS limits user-data to 16KB.

So it might help if the infra provider validates the user-data size.

**Comment by dlipovetsky** [comment]
I like CAPA's current solution, so I'm more than happy to PR a copy of it :smile:

**Comment by detiber** [comment]
@dlipovetsky can we close this as a duplicate of https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/57 then?

**Comment by dlipovetsky** [comment]
@detiber Sure.
