### ISSUE TITLE
Set up image release pipeline

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#52]
/kind feature

**Describe the solution you'd like**
This should implement the k8s_infra image promoter process like what CAPI has done.

https://github.com/kubernetes-sigs/k8s-container-image-promoter

This will be done when we can push an image to the staging branch and have it be promoted to "production" automatically by prow.

**Anything else you would like to add:**

**Comment by chuckha** [comment]
/remove-lifecycle active
/unassign

@liztio did all the hard work i was going to do

The next steps for this ticket are modifying the Makefile to push to the staging bucket found here:

https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L111

/good-first-issue

**Comment by SataQiu** [comment]
Are there any more detailed instructions? Or some examples about this?

**Comment by chuckha** [comment]
@SataQiu I added some additional context above, please let me know if you have any more questions

**Comment by ncdc** [comment]
@chuckha I think we can call this done (except for the automatically pushing to prod part, which we haven't done in any of our repos)?

**Comment by chuckha** [comment]
for sure

/close
