### ISSUE TITLE
task deletion

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#55]
Is there a standard way to delete tasks?

**Comment by chuckha** [comment]
@kfox1111 

can you provide more detail? What is a task?

/priority awaiting-more-evidence

**Comment by kfox1111** [comment]
Ah, there's where this issue went. I'm sorry, I was trying to raise an issue in a different project and missed. I thought I was going crazy when I couldn't find it. :)

Sorry for the noise.
