### ISSUE TITLE
Improve user experience when using an external etcd

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#59]
We must write a few additional certificate files.

The user will be supplying the `etcd.crt` file in addition to the `apiserver-etcd-client.key` and `apiserver-etcd-client.crt` files. They will use the normal etcd secret and CABPK will look for an additional secret, `<cluster-name>-etcd-client` (may not be this name exactly). It will then write these secrets to disk depending on the configuration of the externalEtcd object on the ClusterConfiguration option.

<details>
<summary><b>Original issue click me!</b></summary>
/kind feature

**Describe the solution you'd like**
The current implementation plans for HA consist of deploying using a stacked etcd control plane using the `kubeadm join --experimental-controlplane` feature. There is also a need to eventually support HA clusters where etcd is hosted separately from the control plane.

To simplify the maintenance burden of this approach, we should rely on [etcdmgr](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0031-20181022-etcdadm.md) for managing the etcd components rather than rolling our own custom etcd management.
</details>

**Comment by detiber** [comment]
@ncdc I'm not sure the timeline you had in mind for this, but I'm wondering if this is something that might be better served with a combination of:
- The addition of control plane management primitives added to Cluster API
- A new bootstrap provider for etcdadm

With that combination there shouldn't need to be any changes for the kubeadm bootstrap provider, since we should already have the ability to support external etcd through the exposed kubeadm config (assuming #57 is implemented)

**Comment by fabriziopandini** [comment]
WRT to kubeadm, in order to support this use case it should be defined how to make it available:
1. the list of etcd endpoints (this can go via exposed kubeadm config) 
2. The etcd CA certificate (this can go via files or via secrets).
3. The client certificate for the API server to access etcd (this can go via files or via secrets).

CABPK should detect this case and do not create a new Etcd CA - properly create default Configuration objects (if not provided by the users)

**Comment by chuckha** [comment]
@fabriziopandini I was just playing around with this! 💯 to what you said. I came to the same conclusion.

We support 1 and 2 but we must add support for the api-server-client-cert (3). This will be another file that we can write.

**Comment by fabriziopandini** [comment]
from https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/217#issuecomment-531858072

> I would expect CABPK to move the secret to the cloud init script and bootstrap the node with that certificate.
> If an external CA is in use but only the CA secret is set, use the provided CA to generate the rest of the certificates.

So if I got it right, in case of external etcd:
- CABPK should check for a new secret for 3 holding the client certificate for the API server to access etcd; 
- if the certificate does not exists, CABPK should create it using The etcd CA certificate as a Certificate Authorithy
- finally CABPK should inject the certificate in the cloud init scripts and set etcd configuration accordingly

**Comment by chuckha** [comment]
In the case of external, kubeadm won't be creating the apiserver certs. We only need to provide the CA Cert, not the key along with the apiserver-client key & cert.

To recap:

1 secret:

```
apiserver-client.key: ABC123=
apiserver-client.crt: ABC123=
etcd-ca.crt: ABC123=
```

**Comment by fabriziopandini** [comment]
🤔

**Comment by chuckha** [comment]
To add a little more context to my comment, please see [the `ExternalEtcd` kubeadm object](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#ExternalEtcd). The CAFile is the ca.crt and the cert/key are the apiserver client cert/key.

I will open a PR to kubeadm to improve the documentation and make this more obvious.

**Comment by ncdc** [comment]
We switched to 1 secret per cert or keypair (ca, etcd, front proxy, serviceaccount) just before releasing. The suggestion above combines the etcd ca with the etcd client cert and key. Is that ok, or should we consider using 2 secrets - 1 for the etcd ca, and 1 for the etcd client cert/key?

**Comment by chuckha** [comment]
The reason behind that decision is that we didn't want to block anyone who wanted to integrate with cert-manager. The technical reason was that cert-manager generates one secret per certificate.

It would be good to re-use the etcd secret if we can an then also check for the apiserver-client cert/key.

I'm +1 on 2 secrets as you suggest.

**Comment by ncdc** [comment]
@chuckha would you mind retitling this and updating the description w/the work you'll be doing around the certs/secret & such?

**Comment by chuckha** [comment]
/retitle Improve user experience when using an external etcd
