### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#6]
I propose

> Cluster API Bootstrap Provider Kubeadm: giving your cluster API clusters a kubeadm kick

Timeout: 1 week

**Comment by amy** [comment]
Lol. Lets use this to track overall development of the README documentation. 

/kind documentation

**Comment by chuckha** [comment]
That's too vague. I've seen those tickets I've on basically forever. I'll open a new one to track an initial readme implementation.

/close
