### ISSUE TITLE
Improve Update/Patch of DockerMachine

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#63]
/kind feature

**Describe the solution you'd like**
We are using .Update to update DockerMachines and we should be using patch. One for the object itself and one for the status.

**Anything else you would like to add:**
Take a look here for inspiration:

https://github.com/kubernetes-sigs/cluster-api/blob/62582da077611649856cb2a88ec73c957e8569f5/pkg/controller/cluster/cluster_controller.go#L116-L138

**Comment by amy** [comment]
Can you add information on why a Patch is needed for future reference.

**Comment by detiber** [comment]
Update can fail if the resource version changes. Patch (especially when leveraging the controller-runtime tooling) will only apply a diff and is less likely to conflict.
