### ISSUE TITLE
CI should fail if CRD manifests are out of date

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#73]
/kind bug

**What steps did you take and what happened:**
1. Modify a field in a CRD, such as changing the json tag
1. Run `hack/verify-all.sh`
1. It passes

**What did you expect to happen:**
1. It should fail because the generated manifests are out of date

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API version:
- Cluster API Bootstrap Provider Kubeadm version:
- Cluster API Infrastructure Provider version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by amy** [comment]
Initial thoughts. I'm going to have the verify script run the generate scripts, then run a diff against the PR and what's generated.

**Comment by ncdc** [comment]
> run a diff against the PR

what do you mean by this?

**Comment by amy** [comment]
Run a diff between:
- Actual: the CRD manifests in the PR 
- Expected: the CRD manifests generated from `make manifests` that I'll stick in some temp directory that will clean up after the verify script runs

**Comment by ncdc** [comment]
Ok, thanks. 👍
