### ISSUE TITLE
Define CA pair secret names

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#74]
/kind feature

**Describe the solution you'd like**
In order to allow users to provide their own CA key pairs we should have this provider check a certain location for secrets. A user can upload secrets to this specific location and we will use them. If they don't exist we will create them and then use them.

This may pose a problem of certs disappearing between runs but I think it's ok to ignore that for right now.

Proposal:

| kind | secret name |
|---|---|
| Cluster CA Key | cluster-ca-key |
| Cluster CA Certificate | cluster-ca-cert |
| Etcd CA Key | etcd-ca-key |
| Etcd CA Certificate | etcd-ca-cert |
| FrontProxy CA Key | front-proxy-ca-key |
| FrontProxy CA Certificate | front-proxy-ca-cert |
| ServiceAccount Public Key | service-account-public-key |
| ServiceAccount Private Key | service-account-private-key |

**Anything else you would like to add:**
The idea is to check for the secret, then generate if it's not there or empty and create it with data. If the secret is there and contains data then use that data blindly. We can consider making it smarter in the future.

**Comment by ncdc** [comment]
I think we still want to support multiple clusters in a single namespace, so we'll need to have a way to distinguish between 2 Cluster CA Keys, for example. Right?

**Comment by detiber** [comment]
Indeed, would we be able to prefix the secret names with Cluster.Name?

I also wonder if there is any reason to have separate secrets here, instead of a single secret that deserializes to map[string]string, where the key is the key/cert "name" and the value are the contents.

**Comment by ncdc** [comment]
Prefix/postfix makes sense, but we need to be careful about name length limits - if a cluster has a long name, we may exceed the limit when prepending or appending the cluster name to the secret name.

1 secret sounds like it might work better than multiple.

**Comment by rudoi** [comment]
I wonder if we could get away with naming the secret after the cluster exactly?

**Comment by detiber** [comment]
We *could*, but then there is potential confusion with other secrets, such as the existing `<clustername>-kubeconfig` secret.

**Comment by moshloop** [comment]
> 1 secret sounds like it might work better than multiple

In isolation I agree 1 secret is better than multiple, but if we wanted to interoperate with something like cert-manager than I believe we will need to stick to 1 secret per cert with a `tls.key` and `tls.crt`

**Comment by chuckha** [comment]
1 secret sounds good to me too

**Comment by chuckha** [comment]
Feel free to edit the original post with the new and improved idea, or leave a comment if you cannot edit the post

**Comment by moshloop** [comment]
I don't have issue edit rights 🚫

**Comment by rudoi** [comment]
> We _could_, but then there is potential confusion with other secrets, such as the existing `<clustername>-kubeconfig` secret.

Curious is there anything that stops the `kubeconfig` secret name from exceeding the max length today?

**Comment by ncdc** [comment]
@rudoi nope, we need to address that too 😦

**Comment by rudoi** [comment]
@ncdc understood :) 

Is the scope of this issue just to define the names or to also provide the cert generation work as well?

**Comment by chuckha** [comment]
I was thinking it would also include generating the certs, but if you feel a second ticket with more detail about cert generation makes sense we can definitely add that!

**Comment by rudoi** [comment]
I'm cool to scope this either way. Let's include the cert generation here. @chuckha you had mentioned something about this relying on another PR you were working on?

/assign

**Comment by chuckha** [comment]
@rudoi Yep, just working through the last bit of this https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/42

**Comment by rudoi** [comment]
so I noticed that both the `cloudinit` and the `controllers` packages define a `Certificates` type. Is is ok to throw one of those away here or...?

cc @chuckha

**Comment by fabriziopandini** [comment]
@chuckha @rudoi is the certificate generation included in the part actively worked or not?
AFAIK certificate generation is the latest bit to get the main reconcile workflow in place, and I would like to get this ready for testing as soon as possible; in case the certificate generation is still pending, I will be happy to work on it!

**Comment by rudoi** [comment]
hi @fabriziopandini, yep we're actively working on it. Hope to have something ready for review shortly. :)

**Comment by rudoi** [comment]
Just about done with this but just rebased and need to fix some tests. :smile:
