### ISSUE TITLE
Overlap between cluster network & cabpk configuration

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#78]
/kind bug

**What steps did you take and what happened:**
A user now has several places to define some network settings. One the cluster object and one on the kubeadm config object. We need to make there be only one place where this should be set or at least document it will.

cc @fabriziopandini

**Comment by detiber** [comment]
In my opinion, the precedence should belong to the top-most level object. In this case, we should respect the values defined in the Cluster.

**Comment by detiber** [comment]
Alternatively, we could detect the conflict and error.

**Comment by ncdc** [comment]
Fixed by #141 
/close
