### ISSUE TITLE
Should we honor or ignore cluster.spec.infrastructureReady?

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#85]
In CAPA for v1alpha1, we added code that prevented any Machine instances (ec2 instances) from being created if the cluster infrastructure (VPC, security groups, etc.) wasn't ready yet.

Now that generating bootstrap data is isolated from provisioning Machine infrastructure, I'm wondering if it would be ok to remove the logic in this repo that prevents generating bootstrap data if `cluster.status.infrastructureReady` is `false`. The infrastructure providers _should_ already be gating Machine infrastructure provisioning based on `cluster.status.infrastructureReady`. WDYT?

**Comment by ncdc** [comment]
@chuckha @fabriziopandini

**Comment by detiber** [comment]
@ncdc I'm not entirely sure, since in the case of AWS, the load balancer is created as part of the infrastructure and would be needed for generating the bootstrap data.

**Comment by ncdc** [comment]
@detiber true (and @fabriziopandini mentioned it too in #82)... but we could have this repo require `cluster.status.apiEndpoints` to be valid before continuing (or have the user fill it in manually in the kubeadm config).

**Comment by detiber** [comment]
@ncdc The potential problem would be is that we would just know that the endpoints are set and not that the shared infrastructure is actually ready to be consumed at that point. I think having an explicit InfrastructureReady field allows the cluster infrastructure provider to have a clear marker to signal to the bootstrapper/machine controller that it is ok to proceed is better than implicitly looking for endpoints.

There are also cases today where the API endpoints are not set by the cluster infrastructure and are instead set by the first Machine that is bootstrapped, which would present issues if we are using it to gate machine bootstrapping.

**Comment by ncdc** [comment]
`cluster.spec.infrastructureRef` is optional, so we may need to tell users who leave that unset to patch the status to set `infrastructureReady` to true.

**Comment by detiber** [comment]
yuck, should we provide an optional `noop` cluster infrastructure provider that would just set `infrastructureReady=true` for those use cases?

**Comment by ncdc** [comment]
If we add the `spec.defaultInfrastructureProvider` field you suggested, that could work, although it would end up creating 1 NoopCluster for each Cluster, which seems unnecessary.

For now, I say we honor and require `cluster.status.infrastructureReady` based on the arguments made above, and we can deal with optional infraRef elsewhere. WDYT?

**Comment by detiber** [comment]
sgtm
