### ISSUE TITLE
Wire up AdditionalUserDataFiles to generation code

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#90]
/kind feature

**Describe the solution you'd like**
With #67 and #89, we have an `AdditionalUserDataFiles` field, but it's currently not wired up to anything. We need to plumb it through to the bootstrap data generation.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ykakarap** [comment]
@ncdc I am new to the project. Since this is a "good first issue" I would like to take a look at this.

**Comment by ncdc** [comment]
@ykakarap thanks! We need to plumb this field into the places where we create `cloudinit.NodeInput`, `cloudinit.ControlPlaneInput`, and `cloudinit.ControlPlaneJoinInput`. Is that enough to get started, or do you need more details?

**Comment by ykakarap** [comment]
You also mentioned that there is a CAPA link that I can look at for reference. Can you please provide that?

**Comment by ncdc** [comment]
See e.g. https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c909830772ce8e58497187262f3028b59548b716/pkg/cloud/aws/services/ec2/instances.go#L238-L242
