### ISSUE TITLE
All Updates should be Patches

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#94]
/kind feature

**Describe the solution you'd like**
Refactor the controller to only use Patch to update a config. Don't use update.

/priority important-soon
/milestone v0.1
/good-first-issue
/assign @joonas
/lifecycle active

**Comment by chuckha** [comment]
ok well, assigning to me, but i'm not actually doing the work

/assign

**Comment by chuckha** [comment]
@SataQiu @joonas was already working on this one. In the future if you see life lifecycle active that means it's already being worked on and you should not assign it or work on it without asking the issue owner.

**Comment by SataQiu** [comment]
I'm sorry. I'll be more careful next time
